POST http://localhost:9000/insertProduct/
Content-Type: application/json

{
    "code": "9823",
    "productName":"Tomate",
    "kgQuantity":"25",
    "kgPurchasePrice":"4.00",
    "totalKgPurchasePrice": "100.00",
    "kgResalePrice":"5.20"
}
    